### ISSUE TITLE
Deploy page with GitHub pages

### ISSUE THREAD

**Issue by hdigital** [hdigital/parlgov#3]
Make static page available on [GitHub pages](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site#creating-your-site).

**Comment by hdigital** [comment]
Used default template provided by GitHub pages.

Updated page folder from `public` to `pages`.

```yml
concurrency:
  group: "public"
  cancel-in-progress: false
```

**Comment by hdigital** [comment]
see first deploy — https://github.com/hdigital/parlgov/actions/runs/11029878364

**Comment by hdigital** [comment]
see deploy issue — wrong path specification

---

![image](https://github.com/user-attachments/assets/c169c966-318d-4b65-8c08-dbe588d208be)

**Comment by hdigital** [comment]
correctly specified path in 8b79669


```yml
        with:
          # Upload entire repository
          path: 'public'
```
